### ISSUE TITLE
Error on app start

### ISSUE THREAD

**Issue by amillion3** [egdelwonk/nashdev-jobs#34]
Totally new to this, but trying to contribute! 

Error and die on `yarn run start:dev`. 
node -v is 6.11.2
npm -v is 5.3.0
postgres -V is 9.6.4

Here is my error output:

```No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.

Watch Usage
 › Press a to run all tests.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
2017-08-19 15:41 node[80488] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-08-19 15:41 node[80488] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1020:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nashdev-jobs@0.1.2 test: `jest "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nashdev-jobs@0.1.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/million/.npm/_logs/2017-08-19T20_41_20_619Z-debug.log
error Command failed with exit code 1.
ERROR: "test:watch" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by egdelwonk** [comment]
Try using nvm (node version manager) and install node 8.1 or greater.

**Comment by amillion3** [comment]
Updated to Node 8.4.0, still no luck. I did a `brew install watchman` and it seems to work now.

**Comment by egdelwonk** [comment]
I'll add that step to the readme. What version of watchman are you running?

**Comment by amillion3** [comment]
Sorry for the delay, 4.9.0 is my watchman version.

**Comment by kwelch** [comment]
Jest requires `watchman`. We have had this issue come up before in react-slingshot: https://github.com/coryhouse/react-slingshot/issues/449
